### ISSUE TITLE
TensorType

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/TensorBase#14]
### Description
As a user, I would like to be able to use common types including int and float and also custom types.  Each custom type will need to implement overloads of relational operators for sorting and selecting methods. 
  This implies the need for a TensorType class with a common base class.  The use of a common base class will also make constructing a heterogenous array of tensors of mixed types much easier.

### Objectives
- [ ] TensorType base class
- [ ] TensorType derived classes implementing types for CUDA supported C++ types
- [ ] TensorType derived classes for common Database Types

### Validation
- [ ] Unit test coverage
- [ ] Passing unit tests
- [ ] Working builds on win/linux
