### ISSUE TITLE
TensorCollection IO

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/TensorBase#25]
### Description
TBD

### Objectives
- [x] Schema and metadata serialization using Cereal
- [ ] Tensor data serialization using Eigen data serialization methods
- [ ] Dynamic sharding logic

### Validation
TBD

### References:
- https://uscilab.github.io/cereal/
- https://stackoverflow.com/questions/25389480/how-to-write-read-an-eigen-matrix-from-binary-file
http://www.perbang.dk/rgbgradient/
