### ISSUE TITLE
TensorCollection

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/TensorBase#5]
### Description
As a user, I would like to manage a collection of Tensor that are composed of different dimensions and different types. 

### Objectives
- [x] implement a method for heterogenous tensor storage using type erasure
- [x] unit test coverage

### Validation
- [x] passing unit tests
- [ ] Win/Linux builds
