### ISSUE TITLE
TransactionManager

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/TensorBase#6]
### Description
As a user, I would like to be able to make transactions against the TensorCollection.  I would like to be able to specify commits and rollbacks.  I would like to be able to submit transactions in the form of a lambda function that returns an optional TensorCollection "view" if appropriate.

### Objectives
- [x] Commit and rollback mechanisms both on disk (i.e, write changed shards to disk) and in memory (i.e., apply view changes to tensor tables)
- [x] Transaction execution using lambda functions
- [x] Undo and Redo log
- [x] ACID transactions using e.g., atomics or scopedGuards

### Validation
- [ ] Unit test coverage
- [ ] Passing unit tests
- [ ] Win/Linux builds

**Comment by dmccloskey** [comment]
### Notes 2019-05-21 on ACID
- using Atomic: http://collaboration.cmc.ec.gc.ca/science/rpn/biblio/ddj/Website/articles/DDJ/2007/0712/071101cg01/071101cg01.html
- memento pattern: https://en.wikipedia.org/wiki/Memento_pattern
- TM http://collaboration.cmc.ec.gc.ca/science/rpn/biblio/ddj/Website/articles/DDJ/2007/0712/071101cg01/071101cg01.html
- STM https://gist.github.com/graninas/c7e0a603f3a22c7e85daa4599bf92525
- ScopeGuard https://github.com/ricab/scope_guard
- SharedPtrs https://stackoverflow.com/questions/10270328/the-simplest-and-neatest-c11-scopeguard and https://ideone.com/q8AxNt
