### ISSUE TITLE
TensorCollection operations

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/TensorBase#7]
### Description
As a user, I would like to be able to `select`, `insert into`, `delete`, `update`, `drop`, `create`, `join`, `aggregate`, and perform other typical SQL-like or analytics methods (e.g., mean/count across a column).  I would like to be able to perform these operations on either a single thread, threadpool, or Gpu.

### Objectives
**Implement the following operations**
- [ ] Select
- [ ] Insert Into
- [ ] Delete
- [ ] Update
- [ ] Drop
- [ ] Create
- [ ] Join
- [ ] Sort
- [ ] Etc.,...

### Validation
- [ ] Unit test coverage
- [ ] Passing unit tests
- [ ] Win/Linux build

**Comment by dmccloskey** [comment]
## Overview of common SQL statements
### SELECT
SELECT column1, column2
FROM table1, table2
WHERE [ conditions ]
GROUP BY column1, column2
HAVING [ conditions ]
ORDER BY column1, column2
LIMIT [no of rows] OFFSET [row num]

### INSERT
INSERT INTO TABLE_NAME (column1, column2, column3,...columnN)
VALUES (value1, value2, value3,...valueN);

### UPDATE
UPDATE table_name
SET column1 = value1, column2 = value2...., columnN = valueN
WHERE [condition];

### DELETE
DELETE FROM table_name
WHERE [condition];

### UNION keyword
SELECT column1 [, column2 ]
FROM table1 [, table2 ]
[WHERE condition]

UNION (ALL)

SELECT column1 [, column2 ]
FROM table1 [, table2 ]
[WHERE condition]

### JOIN keyword
SELECT ... FROM table1 CROSS JOIN table2 ...
SELECT table1.column1, table2.column2...
FROM table1
INNER JOIN (LEFT OUTER JOIN, RIGHT OUTER JOIN, FULL OUTER JOIN) table2
ON table1.common_filed = table2.common_field;

### ALTER
ALTER TABLE table1 ADD (DROP)
ALTER DIMENSION dimension1 ADD (DROP)

### CREATE/DROP
CREATE TABLE
CREATE DIMENSION

**Comment by dmccloskey** [comment]
### Notes on supported Tensor Types
- boolToInt
- DatetimeToInt
- supported GPU types see https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#ldg-function

### Notes on Type comparison
- memcmp to compare if C-style arrays are equal https://stackoverflow.com/questions/11305718/comparing-arrays-with-comparison-operator
- re-implement `std::lexicographical_compare` https://en.cppreference.com/w/cpp/algorithm/lexicographical_compare
- Minimal overloads needed with <utility> header https://en.wikibooks.org/wiki/C%2B%2B_Programming/Operators/Operator_Overloading
- list of C++ fundamental types: hhttps://en.cppreference.com/w/cpp/language/types - see https://github.com/apache/arrow/blob/master/cpp/src/arrow/type.h
