### ISSUE TITLE
MemoryManager

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/TensorBase#8]
### Description
As a user, I would like to work with data that is sometimes too large to fit into memory.  Consequently, I would like to be able to dynamically (and seamlessly) query across the entire TensorCollection whether it is on disk or in memory.  I would also like to be able to shard the TensorCollection across multiple hard-drives.  I would also like to be able to serialize the schema of the entire database so as to replicate it on other computers.

### Objectives
- [ ] Serialization support for the data base schema
- [ ] Sharding support for Tensor data
- [ ] Dynamic logic for when to read and write data to the disk
- [ ] Multi-threading support for reading and writing multiple shards at once

### Validation
- [ ] Unit test coverage
- [ ] Passing unit tests
- [ ] Win/Linux builds
